title: Zadan Fairuz
logo: images/Githubprofile.jpg
email: zadanfaidelta@gmail.com
description: Data isn't just numbers; it's the pulse of innovation, turning complexity into impactful solutions that drive lasting value.

resume_url: 'https://drive.google.com/file/d/1MsF9y63MplcJUl4TOveKhPAMUNOgrrfK/view?usp=sharing'

baseurl: "" # the subpath of your site, e.g., "/blog" if your site is hosted at "example.com/blog"
url: "" # the base hostname & protocol for your site, e.g., "http://example.com"

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown